### ISSUE TITLE
Dynamic host demo not loading endpoints with Azure SDK 2.5

### ISSUE THREAD

**Issue by abeven** [Particular/NServiceBus.Azure.Samples#17]
After updating the solution from 2.3 to 2.5, the Host complains that there is no MessageForwardingInCaseOfFaultConfig configured. Once that's added, it runs but the endpoints are never loaded and nothing is logged about failures or exceptions.

**Comment by yvesgoeleven** [comment]
Duplicate of https://github.com/Particular/NServiceBus.Azure.Samples/issues/16

**Comment by yvesgoeleven** [comment]
There were bad binding redirects in the config, causing the endpoints not to load, should be fixed now
